turboquant/blueprints/bet/views.py
from flask import Blueprint, current_app, render_template, request
from flask_login import current_user, login_required

from lib.util_json import render_json
from turboquant.extensions import limiter
from turboquant.blueprints.bet.decorators import coins_required
from turboquant.blueprints.bet.forms import BetForm
from turboquant.blueprints.bet.models.bet import Bet
from turboquant.blueprints.bet.models.dice import roll

bet = Blueprint('bet', __name__, template_folder='templates',
                url_prefix='/bet')


@bet.before_request
@login_required
def before_request():
    """ Protect all of the bet endpoints. """
    pass


@bet.route('/place', methods=['GET', 'POST'])
@coins_required
@limiter.limit('3/second')
def place_bet():
    print("***DEBUG***:", request)
    if request.method == 'GET':
        recent_bets = Bet.query.filter(Bet.user_id == current_user.id) \
            .order_by(Bet.created_on.desc()).limit(10)

        return render_template('bet/place_bet.html', recent_bets=recent_bets)

    form = BetForm()

    if form.validate_on_submit():
        guess = int(request.form.get('guess'))
        wagered = int(request.form.get('wagered'))

        if wagered > current_user.coins:
            error = 'You cannot wager more than your total coins.'
            return render_json(400, {'error': error})

        payout = float(current_app.config['DICE_ROLL_PAYOUT'][str(guess)])
        die_1 = roll()
        die_2 = roll()
        outcome = die_1 + die_2
        is_winner = Bet.is_winner(guess, outcome)
        payout = Bet.determine_payout(payout, is_winner)
        net = Bet.calculate_net(wagered, payout, is_winner)

        params = {
          'user_id': current_user.id,
          'guess': guess,
          'die_1': die_1,
          'die_2': die_2,
          'roll': outcome,
          'wagered': wagered,
          'payout': payout,
          'net': net
        }

        bet = Bet(**params)
        bet.save_and_update_user(current_user)

        return render_json(200, {'data': bet.to_json()})
    else:
        return render_json(400,
                           {'error': 'You need to wager at least 1 coin.'})


@bet.route('/history', defaults={'page': 1})
@bet.route('/history/page/<int:page>')
def history(page):
    paginated_bets = Bet.query \
        .filter(Bet.user_id == current_user.id) \
        .order_by(Bet.created_on.desc()) \
        .paginate(page, 20, True)

    return render_template('bet/history.html', bets=paginated_bets)

turboquant/blueprints/page/views.py
from flask import Blueprint, render_template
from turboquant.blueprints.page.forms import EmailForm

page = Blueprint('page', __name__, template_folder='templates')


# @page.route('/')
# def index():
#    return redirect(url_for('user.login'))

@page.route('/', methods=['GET', 'POST'])
# @page.route('/index/')
def home():

    form = EmailForm()

    # Don't use label
    form.email.label.text = ''

    return render_template('page/home.html', form=form)


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

@page.route('/healthy')
def healthy():
    return ''

turboquant/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from lib.safe_next_url import safe_next_url
from turboquant.blueprints.user.decorators import anonymous_required
from turboquant.blueprints.user.models import User
from turboquant.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            # As you can see remember me is always enabled, this was a design
            # decision I made because more often than not users want this
            # enabled. This allows for a less complicated login form.
            #
            # If however you want them to be able to select whether or not they
            # should remain logged in then perform the following 3 steps:
            # 1) Replace 'True' below with: request.form.get('remember', False)
            # 2) Uncomment the 'remember' field in user/forms.py#LoginForm
            # 3) Add a checkbox to the login form with the id/name 'remember'
            if login_user(u, remember=True):
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('quant.dashboard'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    # return redirect(url_for('user.login'))
    return redirect(url_for('page.home'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
# @login_required # Don't allow sign up. For trial deploy only!!
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():

    form = UpdateCredentials(obj=current_user)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

turboquant/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <!-- <div class="container"> -->
      <div class="navbar-header p-t-10">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}" class="turboquant">
          <!-- <img src="{{ url_for('static', filename='images/snake-eyes.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="Snake Eyes" alt="Snake Eyes"/> -->
          turboquant
        </a><span style="color:gold">BETA</span>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          {% if current_user.is_authenticated %}
            {% if current_user.coins == 0 %}
            <li>
              <a href="#coming-soon">
                <b>Buy Coins</b>
              </a>
            </li>
            {% else %}
            <li>
              <a href="{{ url_for('quant.dashboard') }}">
                <b>Generate Strategy</b>
              </a>
            </li>
            <!-- <li>
              <a href="{{ url_for('bet.place_bet') }}">
                <span class="label label-primary">Place Bet</span>
              </a>
            </li> -->            
            {% endif %}
          {% else %}
            <!-- <li>
              <a href="{{ url_for('billing.pricing') }}">
                <b>Pricing</b>
              </a>
            </li> -->
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.role == 'admin' %}
            <li>
              {% include 'admin/_menu.html' %}
            </li>
          {% endif %}
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false"><b>Account</b>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Session</li>
                <li><a href="{{ url_for('user.logout') }}">Log Out</a></li>
              </ul>
            </li>
          {% else %}
          <li><a href="{{ url_for('user.login') }}">Log In</a></li>
          <!-- <li><a href="{{ url_for('user.signup') }}">Sign Up</a></li> -->
          {% endif %}
        </ul>
      </div>
    <!-- </div> -->
  </nav>
{% endblock %}

{% block footer %}
  <!-- <li><a href="{{ url_for('contact.index') }}">Contact</a></li> -->
<!-- <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
<li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
<li><a href="{{ url_for('page.privacy') }}">About</a></li> -->

{% endblock %}

turboquant/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}
{% import 'billing/macros/billing.html' as billing with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
       href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    
    <link href="{{ url_for('static', filename='styles/menu.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='styles/core.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='styles/components.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='styles/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='styles/pages.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='styles/responsive.css') }}" rel="stylesheet" type="text/css" />
    
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/eonasdan-bootstrap-datetimepicker.4.13.30.min.css') }}">
    <!-- <script
      src="https://code.jquery.com/jquery-1.12.2.min.js"
      integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
      crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v2/"></script> -->

    <!-- <link href="https://fonts.googleapis.com/css?family=Play|Lato" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    
    {% if config['ANALYTICS_GOOGLE_UA'] %}
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', "{{ config['ANALYTICS_GOOGLE_UA'] }}", 'auto');
        ga('send', 'pageview');
      </script>
    {% endif %}
  </head>
  <body>
    {% block header %}{% endblock %}

    {{ billing.card_expiring_warning() }}
    
    <!-- <main class="container"> -->
    <main>
      <!-- {{ flash.render() }} -->

      <!-- <div class="md-margin-top">{% block hheading %}{% endblock %}</div> -->
      {% block heading %}{% endblock %}
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
          </div>
          <div class="col-md-2">
            <ul class="list-inline">
              {% block footer %}{% endblock %}
              <li class="text-muted">turboquant &copy; {{ current_year() }}</li>
            </ul>
          </div>
        </div>
      </div>
    </footer>


    <script src="{{ url_for('static', filename='scripts/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/particler.js') }}"></script>
    <script type="text/javascript">
      // define your configuration (optional)
      var particlerOptions = {
        quantity: 15,
        fillColor: "#16c0ff" //#2dd7ff
      };

      // create particler instance
      var particlerExample = new Particler("particler-instance", particlerOptions);
    </script>
    <script src="{{ url_for('static', filename='scripts/vendor/eonasdan-bootstrap-datetimepicker.4.14.30.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/detect.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/fastclick.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/jquery.slimscroll.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/jquery.blockUI.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/waves.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/jquery.nicescroll.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/jquery.scrollTo.min.js') }}"></script>
    
    <!--Morris Chart-->
    <script src="{{ url_for('static', filename='scripts/vendor/morris.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/raphael-min.js') }}"></script>
    
    <!-- Counter Up  -->
    <script src="{{ url_for('static', filename='scripts/vendor/jquery.waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/jquery.counterup.min.js') }}"></script>
    
    <!-- Dashboard init -->
    <script src="{{ url_for('static', filename='scripts/jquery.dashboard.js') }}"></script>

    <!-- Plotly -->
    <script src="{{ url_for('static', filename='scripts/vendor/d3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/plotly.min.js') }}"></script>

    <!-- App js -->
    <script src="{{ url_for('static', filename='scripts/jquery.core.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/jquery.app.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
    <script src="https://js.stripe.com/v2/"></script>
  </body>
</html>

turboquant/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
<div class="turboquant-login">
  <a href="{{ url_for('page.home') }}" class="turboquant-login-link">
    <!-- <img src="{{ url_for('static', filename='images/snake-eyes-large.jpg') }}"
         class="img-responsive center-block md-margin-bottom"
         width="178" height="176" title="Snake Eyes" alt="Snake Eyes"/> -->
    turboquant
  </a>
</div>
{% endblock %}

{% block footer %}
{% endblock %}