turboquant/blueprints/quant/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template,
    send_file,
    jsonify)
from flask_login import login_required, current_user
from sqlalchemy import text,and_

from turboquant.blueprints.quant.forms import XGBForm, BulkDeleteForm, SearchForm
from turboquant.blueprints.quant.models import Strategy, Ticker, Portfolio
from turboquant.extensions import db
from flask_wtf import Form

from werkzeug.utils import secure_filename
import boto3,json,csv,sys,os

quant = Blueprint('quant', __name__,
                  template_folder='templates', url_prefix='/quant')

ALLOWED_EXTENSIONS = set(['csv'])

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

S3_BUCKET = 'cgiam.sagemaker'

s3 = boto3.client("s3", region_name='us-west-2')
client = boto3.client('lambda', region_name='us-west-2')
sfn = boto3.client('stepfunctions', region_name='us-west-2')

def upload_file_to_s3(file, bucket_name, uid, acl="public-read"):

    try:
        s3.upload_fileobj(
            file,
            bucket_name,
            'u' + str(uid) + '/' + file.filename,
            ExtraArgs={
                "ACL": acl,
                "ContentType": file.content_type
            }
        )

    except Exception as e:
        print("Something Happend: ", e)
        return e

    return "{}".format(file.filename)

@quant.before_request
@login_required
def before_request():
    """ Protect all of the quant endpoints. """
    pass


# Dashboard -------------------------------------------------------------------
@quant.route('/dashboard/')
def dashboard():
    return render_template('quant/page/dashboard.html')


@quant.route('/data/', defaults={'page': 1}, methods=['GET'])
@quant.route('/data/page/<int:page>', methods=['GET'])
def data(page):

    print("*** debug", request)
    print("*** debug", request.method)
    #print("*** debug", request.form.viewkeys())
    #print("*** debug", request.form.keys())
    #print("*** debug", 'upload' in request.form.keys())
    #print("*** debug", 'update' in request.form.keys())
    
    # Use basic form for CSRF token
    form = Form()
    search_form = SearchForm()  
    bulk_form = BulkDeleteForm()

    sort_by = Ticker.sort_by(request.args.get('sort', 'created_on'),
                           request.args.get('direction', 'desc'))
    
    order_values = '{0} {1}'.format(sort_by[0], sort_by[1])
                    
    paginated_tickers = Ticker.query \
                              .filter(Ticker.user_id == current_user.id) \
                              .filter(Ticker.search(text(request.args.get('q', '')))) \
                              .order_by(text(order_values)) \
                              .paginate(page, 2, True) 
            
    return render_template('quant/page/data.html', tickers=paginated_tickers, form=form, bulk_form=bulk_form)


@quant.route('/quant/upload', methods=['POST'])
def tickers_upload():
    # Use basic form for CSRF token
    form = Form()
    
    
    print("upload")
    print("user_file", request.files.getlist('user_file'))
        
    for uf in request.files.getlist('user_file'):
        print("uf:",uf)

        file = uf
        
        """
        These attributes are also available
        
        file.filename
        file.content_type
        file.content_length
        file.mimetype
        """

        #if file.filename == "":
        #    flash('Please select a file', 'danger')
        ##return "Please select a file"

        if file and allowed_file(file.filename):
            file.filename = secure_filename(file.filename)
            output = upload_file_to_s3(file, S3_BUCKET, str(current_user.id) + '/ticker')
            #return str(output)

        else:
            flash('File format not allowed: ' + file.filename, 'danger')


    #elif 'update' in request.form.keys():

    payload = json.dumps({"uid":current_user.id})
    print("*** debug payload:%s" % payload)
    print("*** debug", type(payload))
    payloadb = str.encode(payload)
                    

    response = client.invoke(
        FunctionName='arn:aws:lambda:us-west-2:188444798703:function:list_s3',
        Payload=payloadb,
    )
    
    tickercloud = response['Payload'].read()
    print("***debug respone:", tickercloud)
    print("***debug type:", type(tickercloud))
    tickercloudd = json.loads(tickercloud)
    print("*** debug", type(tickercloudd))
    #print "*** debug", type(tickercloudd[0])
    #print "*** debug", tickercloudd[0]
                    
    #return redirect("quant/page/data.html")
            
            
    # Ticker.query.delete()

    tickercloud_names = [s[0] for s in tickercloudd]
    print("tickercloud_names", tickercloud_names)

    tickerdb = Ticker.query.filter(Ticker.user_id == current_user.id)
    tickerdb_names = [s.tid for s in tickerdb.all()]
    print("tickerdb_names", tickerdb_names)

    # tickercloud: [["AAPL", 233285, "2018-09-08T16:53:24+00:00"], ["ORCL", 197427, "2018-09-08T18:15:59+00:00"], ["SBUX", 226567, "2018-09-08T15:11:44+00:00"]]
    for tic in tickercloudd:
        print("debug: updating ", tic[0])

        # are there any tickers in DB that were removed from cloud?
        if tic[0] in tickerdb_names:
            tickerdb_names.remove(tic[0])

        x = tickerdb.filter(Ticker.tid==tic[0]).first()
        print("x",x)
        if x:
            #x.tid = tic[0]
            x.size = tic[1]
            x.lastmodified = tic[2]
        else:
            t = Ticker(user_id=current_user.id, tid=tic[0], skip=False, size=tic[1], lastmodified=tic[2])
            db.session.add(t)

        #db.session.add(Ticker(user_id=current_user.id, tid=tid,size=size,lastmodified=lastmodified))

    print("tickerdb_names minus cloud:", tickerdb_names)

    for tic in tickerdb_names:
        x = tickerdb.filter(Ticker.tid==tic).first()
        db.session.delete(x)

    db.session.commit()
        
    return redirect(url_for('quant.data'))

@quant.route('/quant/bulk_delete', methods=['POST'])
def tickers_bulk_delete():
    
    form = BulkDeleteForm()

    if form.validate_on_submit():

        if request.form.get('scope') == 'all_items':
            
            ids = Ticker.query.with_entities(Ticker.tid).filter(Ticker.user_id == current_user.id).all()
            # SQLAlchemy returns back a list of tuples, we want a list of strs.
            ids = [str(item[0]) for item in ids] 

        else:
            ids = request.form.getlist('bulk_ids')        
        
        if 'skip' in request.form:
            print("Skip IDS:", ids)
            
            tickersq = Ticker.query.filter(Ticker.user_id == current_user.id)
            for id in ids:
                x = tickersq.filter(Ticker.tid==id).first()
                if request.form.get('scope') == 'all_items':
                    x.skip = False
                else:
                    x.skip = not x.skip
                print("x",x)
            db.session.commit()

        if 'delete' in request.form:
            print("Deleting IDS:", ids)

        flash('{0} ticker(s) were scheduled to be deleted.'.format(len(ids)),
              'success')
    else:
        flash('No tickers were deleted, something went wrong.', 'error')

    return redirect(url_for('quant.data'))


@quant.route('/quant/bulk_strategies', methods=['POST'])
def strategies_bulk_delete():
    
    form = BulkDeleteForm()

    if form.validate_on_submit():
        #ids = Strategy.get_bulk_action_ids_quant(current_user.id,
        #                                         request.form.get('scope'),
        #                                         request.form.getlist('bulk_ids'),
        #                                         'name')

        ## Prevent circular imports.
        #from turboquant.blueprints.billing.tasks import delete_users
        ## sqlalchemy bulk delete
        #delete_users.delay(ids)
        
        if request.form.get('scope') == 'all_items':
            
            ids = Strategy.query.with_entities(Strategy.name).filter(Strategy.user_id == current_user.id).all()
            # SQLAlchemy returns back a list of tuples, we want a list of strs.
            ids = [str(item[0]) for item in ids] 

        else:
            ids = request.form.getlist('bulk_ids')

        if 'portfolio' in request.form:
            print("Portfolio IDS:", ids)
            
            strategiesq = Strategy.query.filter(Strategy.user_id == current_user.id)
            for id in ids:
                x = strategiesq.filter(Strategy.name==id).first()
                if request.form.get('scope') == 'all_items':
                    x.portfolio = False
                else:
                    x.portfolio = not x.portfolio
                print("x",x)
            db.session.commit()

        if 'delete' in request.form:
            print("Deleting IDS:", ids)

        flash('{0} strategies were added/removed from portfolio.'.format(len(ids)),
              'success')
    else:
        flash('No strategies were added/removed from portfolio.', 'error')

    return redirect(url_for('quant.strategies'))

@quant.route('/generate/', methods=['GET','POST'])
def generate():
    print("configuration:",request)
    print("configuration:",request.form)
    print("configuration:",request.form.get('csrf_token'))
    print("current_user:",current_user.id)
    # Pre-populate the email field if the user is signed in.
    #form = XGBForm(obj=current_user)
    form = XGBForm()

    
    if form.validate_on_submit():
        # This prevents circular imports.
        from turboquant.blueprints.quant.tasks import launch_batch_job

        # launch_xgb_job(request.form.get('num-round'),
        #task = launch_sfn_job.delay(current_user.id,
        #                            'AAPL',
        #                            request.form.get('num-round-from'),
        #                            request.form.get('max-depth-from'),

turboquant/blueprints/quant/templates/quant/page/dashboard.html
{% extends 'layouts/app.html' %}

{% block title %}Dashboard{% endblock %}

{% block body %}
<div class="fixed-left">

  <!-- Begin page -->
  <div id="wrapper">

    {% include 'quant/page/side-menu.html' %}

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
      <!-- Start content -->
      <div class="content">
	<div class="container">

	  <!-- Page-Title -->
          <div class="row">
            <div class="col-sm-12">
              <ul class="nav nav-pills nav-pills-custom display-xs-none pull-right">
                <li role="presentation"><a href="#">Today</a></li>
                <li role="presentation" class="active"><a href="#">Yesterday</a></li>
                <li role="presentation"><a href="#">Last Week</a></li>
              </ul>

              <h4 class="page-title">Dashboard<span style="color:orange"> (Placeholder Only)</span></h4>
            </div>
          </div>


          <div class="row">
            <div class="col-lg-4">
              <div class="card-box">
                <div class="dropdown pull-right">
                  <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown"
                     aria-expanded="false">
                    <i class="zmdi zmdi-more-vert"></i>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>

                <h4 class="header-title m-t-0">Daily Sales</h4>


                <div class="row text-center m-t-30">
                  <div class="col-xs-6">
                    <h3 data-plugin="counterup">8,459</h3>
                    <p class="text-muted text-overflow">Total Sales</p>
                  </div>
                  <div class="col-xs-6">
                    <h3 data-plugin="counterup">584</h3>
                    <p class="text-muted text-overflow">Open Compaign</p>
                  </div>
                </div>

                <div class="text-center m-t-10">
                  <div id="morris-donut-example" style="height: 245px;"></div>
                  <ul class="list-inline chart-detail-list m-b-0">
                    <li>
                      <h5><i class="fa fa-circle m-r-5" style="color: #da5461;"></i>Series A</h5>
                    </li>
                    <li>
                      <h5><i class="fa fa-circle m-r-5" style="color: #fe8995;"></i>Series B</h5>
                    </li>
                  </ul>
                </div>
              </div>
            </div><!-- end col -->

            <div class="col-lg-4">
              <div class="card-box">
                <div class="dropdown pull-right">
                  <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown"
                     aria-expanded="false">
                    <i class="zmdi zmdi-more-vert"></i>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>
                <h4 class="header-title m-t-0">Statistics</h4>

                <div class="row text-center m-t-30">
                  <div class="col-xs-4">
                    <h3 data-plugin="counterup">1,507</h3>
                    <p class="text-muted text-overflow">Total Sales</p>
                  </div>
                  <div class="col-xs-4">
                    <h3 data-plugin="counterup">916</h3>
                    <p class="text-muted text-overflow" title="Open Compaign">Open Compaign</p>
                  </div>
                  <div class="col-xs-4">
                    <h3 data-plugin="counterup">22</h3>
                    <p class="text-muted text-overflow">Daily Sales</p>
                  </div>
                </div>

                <div id="morris-bar-example" style="height: 280px;" class="m-t-10"></div>
              </div>
            </div><!-- end col -->

            <div class="col-lg-4">
              <div class="card-box">
                <div class="dropdown pull-right">
                  <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown"
                     aria-expanded="false">
                    <i class="zmdi zmdi-more-vert"></i>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>
                <h4 class="header-title m-t-0">Total Revenue</h4>

                <div class="row text-center m-t-30">
                  <div class="col-xs-6">
                    <h3 data-plugin="counterup">7,653</h3>
                    <p class="text-muted text-overflow">Total Sales</p>
                  </div>
                  <div class="col-xs-6">
                    <h3 data-plugin="counterup">852</h3>
                    <p class="text-muted text-overflow">Open Compaign</p>
                  </div>
                </div>

                <div id="morris-line-example" style="height: 280px;" class="m-t-10"></div>
              </div>
            </div><!-- end col -->

          </div>
          <!-- end row -->


        </div> <!-- container -->

      </div> <!-- content -->

     <!-- <footer class="footer">
        2017 © Flacto. Design by <a href="http://coderthemes.com/" target="_blank" class="text-muted">Coderthemes</a>
      </footer> -->

    </div>
    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


  </div>
  <!-- END wrapper -->

  <script>
    var resizefunc = [];
  </script>

</div>
{% endblock %}

turboquant/blueprints/quant/templates/quant/page/data.html

<!-- Jquery filer css -->
<!-- <link href="assets/plugins/jquery.filer/css/jquery.filer.css" rel="stylesheet" />
<link href="assets/plugins/jquery.filer/css/themes/jquery.filer-dragdropbox-theme.css" rel="stylesheet" />

<link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="assets/css/menu.css" rel="stylesheet" type="text/css" />
<link href="assets/css/core.css" rel="stylesheet" type="text/css" />
<link href="assets/css/components.css" rel="stylesheet" type="text/css" />
<link href="assets/css/icons.css" rel="stylesheet" type="text/css" />
<link href="assets/css/pages.css" rel="stylesheet" type="text/css" />
<link href="assets/css/responsive.css" rel="stylesheet" type="text/css" />

<!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
{% import 'macros/flash.html' as flash with context %}
{% import 'macros/form.html' as f with context %}
{% import 'macros/items.html' as items %}
{% extends 'layouts/app.html' %}

{% block title %}Data{% endblock %}

{% block body %}     

<div class="fixed-left">

  <!-- Begin page -->
  <div id="wrapper">

    {% include 'quant/page/side-menu.html' %}
    
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
      <!-- Start content -->
      <div class="content">
	<div class="container">
          {{ flash.render() }}

          <div class="row">
            <div class="col-sm-12">
              <h4 class="page-title">Upload Data</h4>
            </div>
          </div>          
          
          <div class="row">
            <div class="col-xs-12 card-box">
              <p class="text-muted font-13 m-b-30">
                Here the user can upload their CSV ticker data. The data needs to be in specific format. For this example just use what is already uploaded to S3. In this case the ticker data for AAPL and SBUX. No action required here.
              </p>
            </div>
          </div>
          
          <div class="row">
            <form action="{{ url_for('quant.tickers_upload') }}" method="POST" enctype="multipart/form-data">
              <div class="col-sm-12 card-box">
                {{ form.hidden_tag() }}
                <label class="btn btn-custom btn-file waves-effect waves-light">
                  <input type="file" multiple="multiple" name="user_file" style="display: none"
                         onchange="$('#upload-file-info').html(this.files.length + ' file(s) selected')">
                  Browse
                </label>
                <button type="submit" name="upload" class="btn btn-custom waves-effect waves-light" disabled>Upload <span><i class="fa fa-cloud-upload"></i></span></button>
                <span class="label label-inverse" id="upload-file-info"></span>
              </div>
            </form>
          </div>

          <div class="row">

            <div class="col-sm-12 card-box table-responsive">

              {{ f.search('quant.data') }}
              
              {% call f.form_tag('quant.tickers_bulk_delete') %}
              <div id="bulk_actions" colspan="4">
                <div class="form-inline">
                  {{ f.field(bulk_form.scope, inline=True) }}
                  <button type="submit" name="skip" class="btn btn-warning btn-trans waves-effect waves-light">Skip</button>
                  <button type="submit" name="delete" class="btn btn-danger btn-trans waves-effect waves-light">Delete</button>
                </div>
              </div>

              <table id="datatable" class="table table-striped dt-responsive nowrap">
                <thead>
                  <tr>
                    <!-- <th>created_on</th> -->
                    <!-- <th>id</th> -->
                    <th>
                      <label for="select_all"></label>
                      <input id="select_all" name="select_all" type="checkbox">
                    </th>
                    <th class="col-header">
                      {{ items.sort('tid','ticker') }}
                    </th>
                    <th class="col-header">
                      {{ items.sort('skip','skip') }}
                    </th>
                    <th class="col-header">
                      {{ items.sort('size','size') }}
                    </th>
                    <th class="col-header">
                      {{ items.sort('lastmodified','last modified') }}
                    </th>
                  </tr>
                </thead>
                
                <tbody>
                  {% for ticker in tickers.items %}
                  <tr>
                    <td>
                      <label for="bulk_ids"></label>
                      <input class="checkbox-item" id="bulk_ids" name="bulk_ids"
                             type="checkbox" value="{{ ticker.tid }}">
                    </td>
                    <td>
                      {{ ticker.tid }}
                    </td>
                    <td>
                      {% if ticker.skip == False %}
                      {% else %}
                      <span class="label label-warning"> {{ ticker.skip }} </span>
                      {% endif %}
                    </td>
                    <td>
                      {{ ticker.size }}
                    </td>
                    <td>
                      {{ ticker.lastmodified }}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% endcall %}
              {{ items.paginate(tickers) }}
            </div><!-- end col -->
          </div>
        </div> <!-- container -->
      </div> <!-- content -->
    </div>
    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


  </div>
  <!-- END wrapper -->

  <script>
    var resizefunc = [];
  </script>

  <!-- jQuery  -->
  <!-- <script src="assets/js/jquery.min.js"></script>
       <script src="assets/js/bootstrap.min.js"></script>
       <script src="assets/js/detect.js"></script>
       <script src="assets/js/fastclick.js"></script>
       <script src="assets/js/jquery.slimscroll.js"></script>
       <script src="assets/js/jquery.blockUI.js"></script>
       <script src="assets/js/waves.js"></script>
       <script src="assets/js/wow.min.js"></script>
       <script src="assets/js/jquery.nicescroll.js"></script>
       <script src="assets/js/jquery.scrollTo.min.js"></script> -->

  <!-- Jquery filer js -->
  <!-- <script src="assets/plugins/jquery.filer/js/jquery.filer.min.js"></script> -->

  <!-- App js -->
  <!-- <script src="assets/js/jquery.core.js"></script>
       <script src="assets/js/jquery.app.js"></script> -->

  <!-- page specific js -->
  <!-- <script src="assets/pages/jquery.fileuploads.init.js"></script> -->

</div>

{% endblock %}

turboquant/blueprints/quant/templates/quant/page/side-menu.html
    <!-- ========== Left Sidebar Start ========== -->

    <div class="left side-menu">
      <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
          <ul>

            <!-- <li class="text-muted menu-title">Navigation</li> -->

            <li class="has_sub">
              <a href="/quant/dashboard/" class="waves-effect"><i class="zmdi zmdi-view-dashboard"></i> <span> Dashboard </span> </a>
            </li>

            <li class="has_sub">
              <a href="/quant/data/" class="waves-effect"><i class="fa fa-database"></i> <span> Data </span> </a>
            </li>            

            <li class="has_sub">
              <!-- <a href="/quant/configuration/" class="waves-effect"><i class="zmdi zmdi-settings-square"></i> <span> Configuration </span> </a> -->
              <a href="/quant/generate/" class="waves-effect"><i class="fa fa-cogs"></i> <span> Generate </span> </a>
            </li>

            <li class="has_sub">
              <a href="/quant/strategies/" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> Strategies </span> </a>
            </li>

            <li class="has_sub">
              <a href="/quant/portfolio/" class="waves-effect"><i class="fa fa-pie-chart"></i> <span> Portfolio </span> </a>
            </li>

            <!-- <li class="has_sub">
              <a href="/quant/compile/" class="waves-effect"><i class="fa fa-file-text"></i> <span> Compile </span> </a>
            </li> -->              

            <!-- <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> User Interface </span> <span class="menu-arrow"></span> </a>
              <ul class="list-unstyled">
                <li><a href="ui-buttons.html">Buttons</a></li>
                <li><a href="ui-cards.html">Cards</a></li>
                <li><a href="ui-typography.html">Typography </a></li>
                <li><a href="ui-checkbox-radio.html">Checkboxs-Radios</a></li>
                <li><a href="ui-icons.html">Icons</a></li>
                <li><a href="ui-modals.html">Modals</a></li>
                <li><a href="ui-images.html">Images</a></li>
                <li><a href="ui-components.html">Components</a>
              </ul>
            </li>

            <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-case"></i> <span> Admin UI </span> <span class="menu-arrow"></span> </a>
              <ul class="list-unstyled">
                <li><a href="admin-masonry.html">Masonry</a></li>
                <li><a href="admin-notification.html">Notification</a></li>
                <li><a href="admin-range-slider.html">Range Slider</a></li>
                <li><a href="admin-sweetalert.html">Sweet Alert</a>
              </ul>
            </li>

            <li class="has_sub">
              <a href="/quant/widgets/" class="waves-effect"><i class="zmdi zmdi-layers"></i> <span> Widgets </span> </a>
            </li>

            <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-text"></i><span class="label label-default pull-right">6</span><span> Forms </span> </a>
              <ul class="list-unstyled">
                <li><a href="form-elements.html">Form Elements</a></li>
                <li><a href="form-advanced.html">Advanced Form</a></li>
                <li><a href="form-validation.html">Form Validation</a></li>
                <li><a href="form-wizard.html">Form Wizard</a></li>
                <li><a href="form-summernote.html">Summernote</a></li>
                <li><a href="form-uploads.html">Form Uploads</a></li>
              </ul>
            </li> -->

            <!-- <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> Tables </span> <span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                <li><a href="tables-basic.html">Basic Tables</a></li>
                <li><a href="tables-datatable.html">Data Table</a></li>
                <li><a href="tables-editable.html">Editable Table</a></li>
              </ul>
            </li> -->

            <!-- <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-chart"></i><span> Charts </span> <span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                <li><a href="chart-flot.html">Flot Chart</a></li>
                <li><a href="chart-morris.html">Morris Chart</a></li>
                <li><a href="chart-chartist.html">Chartist Charts</a></li>
                <li><a href="chart-other.html">Other Chart</a></li>
              </ul>
            </li>

            <li class="has_sub">
              <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-map"></i><span> Maps </span> <span class="menu-arrow"></span></a>
              <ul class="list-unstyled">
                <li><a href="map-google.html">Google Maps</a></li>
                <li><a href="map-vector.html">Vector Maps</a></li>
              </ul>
            </li> -->

          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

      </div>
    </div>
    <!-- Left Sidebar End -->